export const COMMENT_MARKER = "<!-- readme-doctor-report -->";

interface GitHubComment {
  id: number;
  body?: string | null;
  user?: { type?: string | null } | null;
}

export interface PullRequestCommentOptions {
  apiUrl: string;
  repository: string;
  pullRequestNumber: number;
  token: string;
  body: string;
  fetchImpl?: typeof fetch;
}

export function buildPullRequestComment(report: string): string {
  const footer = "_Generated by Readme Doctor. This comment is updated on each run._";
  const available = 60_000 - COMMENT_MARKER.length - footer.length - 16;
  const truncated = report.length > available
    ? `${report.slice(0, available)}\n\n… report truncated`
    : report;
  return `${COMMENT_MARKER}\n${truncated}\n\n${footer}`;
}

export async function upsertPullRequestComment(options: PullRequestCommentOptions): Promise<"created" | "updated"> {
  const request = options.fetchImpl ?? fetch;
  const base = `${options.apiUrl}/repos/${options.repository}`;
  const headers = {
    Accept: "application/vnd.github+json",
    Authorization: `Bearer ${options.token}`,
    "X-GitHub-Api-Version": "2022-11-28",
    "Content-Type": "application/json",
  };
  const commentsResponse = await request(
    `${base}/issues/${options.pullRequestNumber}/comments?per_page=100`,
    { headers },
  );
  if (!commentsResponse.ok) {
    throw new Error(`Unable to list pull request comments: ${commentsResponse.status} ${await commentsResponse.text()}`);
  }

  const comments = await commentsResponse.json() as GitHubComment[];
  const existing = comments.find((comment) =>
    comment.user?.type === "Bot" && comment.body?.includes(COMMENT_MARKER),
  );
  const endpoint = existing
    ? `${base}/issues/comments/${existing.id}`
    : `${base}/issues/${options.pullRequestNumber}/comments`;
  const response = await request(endpoint, {
    method: existing ? "PATCH" : "POST",
    headers,
    body: JSON.stringify({ body: options.body }),
  });
  if (!response.ok) {
    throw new Error(`Unable to ${existing ? "update" : "create"} pull request comment: ${response.status} ${await response.text()}`);
  }
  return existing ? "updated" : "created";
}
